---
- include_vars: secured.yml

- name: add user into the wheel group
  user:
    name: "{{ new_user }}"
    groups: wheel
    password: "{{ new_user_password }}"

- name: authorized keys
  authorized_key:
    user: "{{ new_user }}"
    key:  "{{ lookup('file', '/home/{{ current_user }}/.ssh/id_rsa.pub') }}" 

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin"
    line: "PermitRootLogin no"
    backrefs: yes
    state: present
  notify:
    - restart sshd

- name: Disallow SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
    backrefs: yes
    state: present
  notify:
    - restart sshd

- name: change hostname 
  hostname: 
    name: "{{ inventory_hostname }}"
